services:
  postgres:
    container_name: postgres-sql-wac
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: whatsapp-clone
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - whatsapp-clone  # Cambié network_mode a networks
    restart: unless-stopped
  keycloack:
    container_name: keycloack-wac
    image: quay.io/keycloak/keycloak:26.0.0  # Tenías mal escrito "keycloak"
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin  # Tenías mal escrito "KEYCLOAK"
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - whatsapp-clone
    command:
      - "start-dev"

networks:
  whatsapp-clone:
    driver: bridge

volumes:
  postgres:
    driver: local
